locations:
  url: http://geodb-free-service.wirefreethought.com/v1/geo/cities?namePrefix=<CIDADE>&minPopulation=&location=&radius=&limit=5&offset=0&hateoasMode=false&languageCode=pt

airport:
  url: https://openflights.org/php/apsearch.php

car:
  url:
    brand: http://fipeapi.appspot.com/api/1/carros/marcas.json
    vehicles: http://fipeapi.appspot.com/api/1/carros/veiculos/code.json

spring:
  datasource:
    url: jdbc:h2:mem:javadb
    driverClassName: org.h2.Driver
    username: sa
    password: mypass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.jks
#    key-store-password: password
#    key-alias: 1
#    enabled: true
#    key-password: password
#  port: 8443